# Generated by Django 4.0.3 on 2022-03-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
