# Generated by Django 4.0.3 on 2022-03-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='monthlybill',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='nopih',
            field=models.CharField(default='SOME STRING', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='states',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
